### ISSUE TITLE
Patcher does not work on iosevka fonts

### ISSUE THREAD

**Issue by sh1boot** [sh1boot/numderline#1]
They look the same with or without the patch.  Not sure why.

**Comment by sh1boot** [comment]
@be5invis could I trouble you for any insight here?  This project makes up a handful of extra glyphs and then adds font features to put them in place of ASCII digits as thousand separators, but it seems to work on everything except for Iosevka.  You've probably examined this code in the past as it's a fork of the numderline tool discussed in be5invis/Iosevka#453.

I wondered if it somehow conflicted with the pre-existing feature:
https://github.com/be5invis/Iosevka/commit/19e7a1a5db577d3ee952d0b3d75dbfaac4a56076
but I can't see how.

**Comment by be5invis** [comment]
Well Ioesvka is a pretty "extreme" font so maybe FontForge won't work well with it.

**Comment by sh1boot** [comment]
Maybe... although I think the nerdfonts project seems to be able to apply its patches using the same tool.

Anyway, I'm back into the concerted effort to make sense of large numbers again, and something I've just noticed about Iosevka is that `+THND` conflicts with `+onum`.  This tool creates features to touch the same digits as those two features are fighting over, so I wonder if it's something about the order in which different features are applied.  Maybe even if `+THND` isn't switched on, perhaps the digits get assigned non-default code-points?  Is there some way I can figure out what code points I would need to search for instead of 0x30-0x39 ?

I would like to figure this out for my own selfish self.  Simply because I want to use Iosevka, _and_ I want to use the digit-grouping policy that this patcher implements (insert spaces, never orphan a lone digit, support hexadecimal).

Another approach might be if I just filed a feature request in Iosevka, and pointed to this code.

**Comment by sh1boot** [comment]
Using this tool: https://github.com/harfbuzz/uharfbuzz#example

I can see that before patching, features `onum` and `THND` work as expected, and that after patching, using feature `dgsp` works as expected while `onum` and `THND` are both broken.  In both cases, when `THND` or `dgsp` is not in use, it does _not_ change the digit glyphs.

Something is obviously broken, though, because if `dgsp` is not in use then `THND` should not break.

So, so much for the theory that the `THND` feature is interfering.  Maybe the glyphs aren't being properly edited, or maybe the render I'm using (OSX) behaves differently from harfbuzz for some reason.

Looking in FontForge, it turns out that the new glyphs have been added, but they've not been edited as expected.  They're exactly the same as the glyphs they were based on.

**Comment by sh1boot** [comment]
For the benefit of whomever; the issue turned out to be that Iosevka digit glyphs are mostly blank with "references" to other glyphs with the outlines in them.  The patcher was reading and reshaping the blank area without updating the references.

Subsequently, having realised a reference is a thing, I've decided to make this patcher use references exclusively instead of trying to reshape the outlines which are usually (but not always) available.
